<?php

namespace AppBundle\Repository;

/**
 * BordersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BordersRepository extends \Doctrine\ORM\EntityRepository
{
}
