<?php

namespace AppBundle\Repository;

/**
 * TranslationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslationsRepository extends \Doctrine\ORM\EntityRepository
{
}
