AppBundle\Entity\Borders:
    type: entity
    manyToOne:
        country:
          targetEntity: Country
          inversedBy: borders
          joinColumn:
            name: country_id
            referencedColumnName: id
    table: borders
    repositoryClass: AppBundle\Repository\BordersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        border:
            type: string
            length: 255
    lifecycleCallbacks: {  }
