AppBundle\Entity\Languages:
    type: entity
    manyToOne:
        country:
          targetEntity: Country
          inversedBy: languages
          joinColumn:
            name: country_id
            referencedColumnName: id
    table: languages
    repositoryClass: AppBundle\Repository\LanguagesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        language:
            type: string
            length: 255
    lifecycleCallbacks: {  }
